### ISSUE TITLE
Unable to stop audio with media_stop service

### ISSUE THREAD

**Issue by timknowlden** [jjlawren/sonos_cloud#12]
I am able to start media playing. In this instance a google hosted mp3. However using media_stop or turn_off service it will not stop it. I cannot stop it in the sonos app. 

I have found the only way to stop is to play a TTS message.

**Comment by jjlawren** [comment]
There is currently not a way to stop audio playback once it has begun using this component. The intention for this custom component is to allow playing short TTS/alert sounds, not music or long-playing audio. The built-in Sonos integration should  be used for music playback and controls.

**Comment by timknowlden** [comment]
> There is currently not a way to stop audio playback once it has begun using this component. The intention for this custom component is to allow playing short TTS/alert sounds, not music or long-playing audio. The built-in Sonos integration should be used for music playback and controls.

Okay not a problem. I thought it would have been a good solution to couple with my electric fire to play audio of fire sounds at a low volume whilst it’s on. As this plays along side anything else that’s already on.

**Comment by jjlawren** [comment]
Interesting use-case that I hadn't considered. I'm not seeing an API call that allows us to cancel a clip in progress. Perhaps there's a clever way to play an empty clip on top of one that's already playing to "cancel" it, but it would take some experimenting.

**Comment by timknowlden** [comment]
Everyone has a unique case for sow integration 👍

Yes I will experiment and a short empty audio clip will probably do it.

**Comment by jjlawren** [comment]
Hi @timknowlden, have you had any luck with your experiments?

**Comment by timknowlden** [comment]
No I stopped going down that route and got a google home mini for £5 second hand and use that for the fire audio

**Comment by jjlawren** [comment]
Okay, thanks for the update. I'm going to close this issue for now as there's not a clear way to support the request.
