### ISSUE TITLE
{"error":"invalid_request"}

### ISSUE THREAD

**Issue by Hoekeren** [jjlawren/sonos_cloud#15]
I am trying to add the Sonos Cloud integration, but after the login page at api.sonos.com I just get :

{"error":"invalid_request"}

Any idea what is wrong?

Looking forward to hearing from you.
kind regards Christian

**Comment by jjlawren** [comment]
Hard to tell. Did you follow all of the steps in the readme? Is there anything in your HA logs?

**Comment by Hoekeren** [comment]
__

> Hard to tell. Did you follow all of the steps in the readme? Is there anything in your HA logs?

Sorry - my bad. I had skipped a section. Everything is working as expected.
