### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by romtram** [jjlawren/sonos_cloud#17]
22-01-28 10:45:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of SONOS AudioClip TTS
22-01-28 10:45:25 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of SONOS AudioClip TTS

**Comment by jjlawren** [comment]
@romtram that's not from this project, but from a different add-on that you have installed. Perhaps <https://github.com/kevinvincent/hassio-addons/tree/master/sonos-audioclip-tts>?

**Comment by romtram** [comment]
Yes you are right! Sorry, close the report! Thank you
