### ISSUE TITLE
State of the special audio clip media players is always Idle

### ISSUE THREAD

**Issue by ervwalter** [jjlawren/sonos_cloud#18]
I have an automation (in node red, actually), that implements a TTS queue so that if another TTS event starts before the previous one finishes, it gets queued up instead of interupting the one in progress.  Previously, I was doing this by watching for when the state of the media_player.whatever device went back to Idle.  But that doesn't seem to work with these new entities as they always appear to be idle.  Is there any way to know when the audio clip ends?

**Comment by jjlawren** [comment]
Unfortunately not, sorry. Ideally this would work cooperatively with the built-in integration, but that's not a trivial task for now.

**Comment by ervwalter** [comment]
Even without this, this is super helpful. Thanks!
