### ISSUE TITLE
Error Logged on Start/Restart of HA

### ISSUE THREAD

**Issue by rcblackwell** [jjlawren/sonos_cloud#19]
I stumbled upon sonos_cloud while searching for help on making Sonos announcements. I installed the integration through HACS then configured it through the Add Integrations Menu. All directions for setup were followed and the integration is working okay for announcements. Since installing the integration, errors have been noted in HA logs when HA is rebooted. No errors occur afterwards, only on first start. Research into the error suggests the integration may be using a deprecated call. See [https://github.com/home-assistant/core/issues/15394](url) and [https://github.com/home-assistant/core/issues/22877](url) for details.

```
Logger: homeassistant.components.homekit.util
Source: components/homekit/util.py:311
Integration: HomeKit (documentation, issues)
First occurred: 2:12:30 PM (4 occurrences)
Last logged: 2:12:30 PM

media_player.livingroom_sonos_l_r_2 does not support any media_player features
media_player.breakfast_sonos_2 does not support any media_player features
media_player.kitchen_sonos_2 does not support any media_player features
media_player.workshop_sonos_2 does not support any media_player features
```
HA Details follow;
## System Health

version | core-2022.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.91
arch | aarch64
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4909
Installed Version | 1.22.0
Stage | running
Available Repositories | 977
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 22, 2022, 7:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 9.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (10.0.2), Node-RED (10.4.0), Home Assistant Google Drive Backup (0.105.2), Samba share (9.5.1), Check Home Assistant configuration (3.9.0), Network UPS Tools (0.9.1), Studio Code Server (4.1.0), Z-Wave JS (0.1.52)

</details>

<details><summary>Lovelace</summary>

dashboards | 6
-- | --
resources | 5
views | 26
mode | storage

</details>

**Comment by jjlawren** [comment]
That seems expected as the `media_player` entities created here don't actually provide any features a "normal" one would. They can only be used for the `media_player.play_media` service call (and those that rely that service such as TTS). See [here](https://github.com/jjlawren/sonos_cloud/blob/b0ad333dec7455ddd417a5e29d1af82184c2a2a9/custom_components/sonos_cloud/media_player.py#L55-L58).

You should just exclude these entities from your Homekit config and the errors will go away.
