### ISSUE TITLE
Supports v2 players only

### ISSUE THREAD

**Issue by GledholtHall** [jjlawren/sonos_cloud#2]
I think this only works with v2 players.  I have two separate Sonos accounts (not mixed systems)

If I log into a my account containing v1 players (only) then TTS doesn't work.  If I log into the v2 account containing only v2 players it works fine.

**Comment by jjlawren** [comment]
Try the 0.0.2 release. It should now add speakers from multiple systems and alert you if a specific speaker does not support the `AUDIO_CLIP` feature (which is the main point of this custom component).

**Comment by mycanaletto** [comment]
I confirm, my system is in v1 and the only Sonos that appears is the Sonos AMP which is compatible v2

**Comment by jjlawren** [comment]
Check your HA logs. In 0.0.2 there is a warning for each speaker that is not supported.

**Comment by mycanaletto** [comment]
OK, only v2 devices are supported. Maybe you need to update the redme...

**Comment by jjlawren** [comment]
I think it's based on the hardware support more than S1/S2. What specific models are not supported for you?

**Comment by mycanaletto** [comment]
AMP : OK
Play 1 : fail
Play 3 : fail
Connect :  Fail
Connect:Amp  : Fail

**Comment by jjlawren** [comment]
Are all of those still on S1?

**Comment by mycanaletto** [comment]
yes

**Comment by jjlawren** [comment]
Ok. The Sonos documentation is a bit unclear here. It still says that Play:1 models do not support audio clips, but mine (on S2) works fine. Same with a S2-compatible Connect. It must be a combination of hardware + firmware where some S1 devices have support and others have been added on more recent versions.

**Comment by mycanaletto** [comment]
Attention, there are Sonos 1 and Sonos Play 1 which are different. There are also several generations of devices and Sonos seeks to eliminate the old ones to sell new ones...

**Comment by jjlawren** [comment]
I'm aware of the differences and I've tested both Play:1 and One models successfully on S2. Perhaps there are very old revisions of the Play:1 which cannot support this.

**Comment by mycanaletto** [comment]
Maybe just that some functions are disabled in S1. I stay in S1 because I have old devices (connect) that are not supported in S2.

**Comment by cstrand89** [comment]
Hi. I am having an issue. Two Sonos One v2 speakers grouped as Living Room. When I use this integration and select the Living room speak only the left speaker does the TTS rather than both as per the normal sonos integration
