### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by AarvdH** [jjlawren/sonos_cloud#25]
Hi, I really don't know what I am doing wrong, but it's now for three weeks that my Sonos cloud isn't working anymore. It was always just fine. Didn't change anything but suddenly I don't have no cloud entity's anymore. I de installed and installed the HACS integration now so many times, alsi tried a new sonos developer account, another key, but nothing helps. To problem is dlso that I am not getting any error. Nothing happens. Its installing from, HACS, then restart, then the integration. Since 22.06  another layout authentication. No errors, but also no entity's. What musst I do to fix this? Really don't no where to look anymore. Tryed also other test environments here, but everywhere the same problem. The normal Sonos integration is working just fine...

Thanks.

**Comment by jjlawren** [comment]
What versions of HA and `sonos_cloud` are you running?

If you find the Sonos Cloud integration on your [Integrations](https://my.home-assistant.io/redirect/integrations/) page, does it show that it's loaded properly and links to the devices & entities?

You can try to enable debug logging by setting this in your `configuration.yaml`:

```yaml
logger:
  logs:
    custom_components.sonos_cloud: debug
```

At a minimum (at `INFO` log level), you should be seeing log messages like this:
```
[homeassistant.loader] We found a custom integration sonos_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
[homeassistant.setup] Setting up sonos_cloud
[homeassistant.setup] Setup of domain sonos_cloud took 0.0 seconds
[homeassistant.components.media_player] Setting up media_player.sonos_cloud
```

**Comment by AarvdH** [comment]
Hi there,
I wrote a message this morning about the things you asked. Somehow that message is dissapeared. But in the meantime I know whats going wrong. Its my own fault and I opogize for the inconvenient. Somehow, the browser was directly logging in with the wrong google account to authorize the Sonos cloud. Now its working just fine again.
Sorry and have a nice weekend.
Great integration you made. Thanks.

Hans.
