### ISSUE TITLE
Error during start up

### ISSUE THREAD

**Issue by groenmarsmannetje** [jjlawren/sonos_cloud#26]
I get the following error during startup.

```
Error setting up entry Configuration.yaml for sonos_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sonos_cloud/__init__.py", line 93, in async_setup_entry
    for household in households:
TypeError: 'NoneType' object is not iterable
```

I am using HA version 2022.6.4
And integration version 0.3.0

**Comment by AgentHawk** [comment]
same

looks like 2022.6 broke something

**Comment by jjlawren** [comment]
I'm wondering if there was an issue with the Sonos API during that time. Can you try to reload the integration or restart HA to see if the problem persists?

**Comment by sgeeurickx** [comment]
Same for me, probably since 2022.6

**Comment by groenmarsmannetje** [comment]
I just did a restart again of HA and now it seems to work again.

**Comment by AgentHawk** [comment]
got it again

**Comment by jjlawren** [comment]
I've added better error handling in 0.3.1. I'm 99% sure these issues are caused by transient HTTP errors that were being silently ignored.

**Comment by mycanaletto** [comment]
Sometimes it works, sometimes not... (since 2022.11 I would say)
![image](https://user-images.githubusercontent.com/45459269/207043985-7f155ce6-c734-43de-97af-43d24e8c7a9b.png)
