### ISSUE TITLE
Not creating a second speaker for all sonos speakers.

### ISSUE THREAD

**Issue by Joris-23** [jjlawren/sonos_cloud#27]
I have 6 sonos speakers in my house and for 2 of them (one SL), it's not creating a second speaker and thus not using the audioclip feature.

**Comment by jjlawren** [comment]
Is there anything special about these speakers? Are they part of a home theater or stereo pair? If so, refer to [this section](https://github.com/jjlawren/sonos_cloud#home-theater--stereo-pair-configurations) from the docs.

Otherwise, are there any warnings in the logs?

**Comment by jjlawren** [comment]
@Joris-23 do you have any updates on your side?
