### ISSUE TITLE
Setup Failed

### ISSUE THREAD

**Issue by acs-lux** [jjlawren/sonos_cloud#3]
Hi,

I performed all as per instructions but get this error.

Logger: homeassistant.config_entries
Source: custom_components/sonos_cloud/__init__.py:74
Integration: Sonos Cloud (documentation, issues)
First occurred: 1:18:58 PM (1 occurrences)
Last logged: 1:18:58 PM

Error setting up entry Configuration.yaml for sonos_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sonos_cloud/__init__.py", line 74, in async_setup_entry
    household = households[0]["id"]
IndexError: list index out of range

I have the Sonos integration already. Does it have to be removed first? If so I must have missed that in the instructions.

Ive restarted a few times but its the same.

I have 3 x Sonos Play 1 so not sure if that is important.

**Comment by acs-lux** [comment]
Removed and tried again and now its working, strange

**Comment by jjlawren** [comment]
It can work alongside the built-in Sonos integration without issue. It looks like there was an unexpected payload received from the Sonos cloud endpoint. Can probably add some validation to make this error a bit cleaner.
