### ISSUE TITLE
Home Assistant Warning since HA 2022.10

### ISSUE THREAD

**Issue by sparment** [jjlawren/sonos_cloud#36]
I'm seeing the warning below consistently in the HA Logs:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest

**Comment by jjlawren** [comment]
I'm not seeing how this relates to `sonos_cloud`. Do you have more info that implies that?

**Comment by sparment** [comment]
I'm pretty sure the warning corresponds when automations in my setup use Sonos_cloud; but I'm not certain. If you haven't seen this elsewhere or how it can relate to Sonos_cloud, I'll close this issue and keep investigating on my end. Apologies for opening the issue so quickly.

**Comment by jjlawren** [comment]
If you find something that shows it might be related please feel free to reopen or submit a new issue.

**Comment by sparment** [comment]
I did some troubleshooting and have narrowed it down to the Sonos_cloud and the use of a tts service call:

     - service: tts.google_translate_say
       data_template:
          entity_id: "{{ sonos_cloud_entity }}"
         message: "{{ message }}"

The service works - the message plays on the appropriate entity but results in a warning in the log.

The warning comes up after a reboot of HA and the first run of this service. Subsequent runs do not result in warnings.

**Comment by jjlawren** [comment]
Thanks for following up. Turns out this was introduced by a change in HA core in https://github.com/home-assistant/core/pull/72593.

I've pushed a new `sonos_cloud` release ([0.3.3](https://github.com/jjlawren/sonos_cloud/releases/tag/0.3.3)) which addresses the warning.
