### ISSUE TITLE
Local media playback not working despite chime and TTS working alright

### ISSUE THREAD

**Issue by doodlebro** [jjlawren/sonos_cloud#37]
I'm using nodered to create automations. Got the CHIME and TTS tests working fine (copied from the examples in the readme).  For some reason the local media examples don't work. My file is called "youve_got_mail.mp3" and I can play it fine through the HA media UI. There are no API errors in the nodered flow, so HA seems to accept the path for the media, it just never plays the requested mp3 on my Sonos device.

**Comment by jjlawren** [comment]
You're able to play the file through the Media UI but you're unable to create an automation? Have you tried using the "Play media" action in the UI automation builder?
