### ISSUE TITLE
ikea sonos symfonisk, music stop to play

### ISSUE THREAD

**Issue by Czara** [jjlawren/sonos_cloud#4]
Hi, 

Thank you for this job, it works, but this function does'nt work : 

Audio played in this manner will reduce the volume of currently playing music, play the clip on top of the music, and then automatically return the music to its original volume.

Music stop to play.

I use ikea sonos symfonisk speaker.

Thank you.

**Comment by jjlawren** [comment]
Make sure you use the `media_player` entity created by the `sonos_cloud` integration, not the one associated with the existing `sonos` integration.

**Comment by Czara** [comment]
Hello, 

Oh yeah !!! It's good, I used a original entity ... I'm so stupid ;)

Thank you.

**Comment by jjlawren** [comment]
Great. I wanted to avoid having separate entities but I don't see a simple way of doing that today.

**Comment by Czara** [comment]
Good luck, and many thanks for this job !
