### ISSUE TITLE
Retrying setup: None error

### ISSUE THREAD

**Issue by bvanbokhoven** [jjlawren/sonos_cloud#44]
After setting up Sonos Cloud in HA Core I receive the message 'Retrying setup: None' error. No Sonos devices are found. The initial setup was without any issues (login etc). My Sonos setup is based on S1 speakers.

**Comment by jjlawren** [comment]
Unfortunately some older devices don't support the cloud functionality: https://github.com/jjlawren/sonos_cloud#Device-support.
