### ISSUE TITLE
Is this intended to completely replace the Sonos integration provided by HASS?

### ISSUE THREAD

**Issue by duro** [jjlawren/sonos_cloud#7]
....or it it only to be used for notification alerts?

If the later, should I leave the devices/entities from the HASS Sonos integration for when I want to control music more like a normal music player?

**Comment by jjlawren** [comment]
Just to provide a better experience for TTS/alerts as the specific API it uses for this is cloud-only. The built-in integration is preferred for everything else as it's local and provides push-based updates.
