### ISSUE TITLE
User error

### ISSUE THREAD

**Issue by thomassandsor** [jjlawren/sonos_cloud#8]
So i'm not sure what I am doing wrong, but something isn't working for me:) 

I followed your guide and now I see my 5 devices in the sonos cloud entities. I have the following config setup in yaml
![image](https://user-images.githubusercontent.com/33664322/143962472-2dd5d3cb-1102-4b9d-b661-dd9c662092a7.png)

I try to click the different speakers within lovelace and choose the "text to speach". I write in some text, but I don't hear anything. Is there another way this should be working or I should be testing? :) I am fairly new at the whole HA

**Comment by jjlawren** [comment]
Have you checked this section in the instructions? https://github.com/jjlawren/sonos_cloud#limitations

**Comment by thomassandsor** [comment]
![image](https://user-images.githubusercontent.com/33664322/144024850-2c579278-f063-4cd9-af25-bc360f506fb8.png)
This is what I get when I add the lines
![image](https://user-images.githubusercontent.com/33664322/144025124-afc7f11e-3bd6-4d38-8036-6e3e0e67b33c.png)
I subbed the URL for my external URL. I am using 2 factor authentication, and not sure that could be a problem? 

Or are you referring to a folder having to be available online to the rest of the world "www"? This might be very obvious, but not sure if I am right around the corner to make this work, or if I am far away:)

**Comment by thomassandsor** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/cloud/tts.py:101
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:59:34 PM (1 occurrences)
Last logged: 4:59:34 PM

[547521516688] No authentication found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 184, in async_say_handle
    url = await tts.async_get_url_path(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 372, in async_get_url_path
    filename = await self.async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 384, in async_get_tts_audio
    extension, data = await provider.async_get_tts_audio(message, language, options)
  File "/usr/src/homeassistant/homeassistant/components/cloud/tts.py", line 101, in async_get_tts_audio
    data = await self.cloud.voice.process_tts(
  File "/usr/local/lib/python3.9/site-packages/hass_nabucasa/voice.py", line 211, in process_tts
    await self._update_token()
  File "/usr/local/lib/python3.9/site-packages/hass_nabucasa/voice.py", line 169, in _update_token
    resp = await cloud_api.async_voice_connection_details(self.cloud)
  File "/usr/local/lib/python3.9/site-packages/hass_nabucasa/cloud_api.py", line 22, in check_token
    await cloud.auth.async_check_token()
  File "/usr/local/lib/python3.9/site-packages/hass_nabucasa/auth.py", line 167, in async_check_token
    if not self._authenticated_cognito.check_token(renew=False):
  File "/usr/local/lib/python3.9/site-packages/hass_nabucasa/auth.py", line 211, in _authenticated_cognito
    raise Unauthenticated("No authentication found")
hass_nabucasa.auth.Unauthenticated: No authentication found


This is what the log says.. I am not usind Nabu Case. I setup everything with DuckDNS (just see a few references arround the place with this).

**Comment by jjlawren** [comment]
If you switch to the `cloud` platform for `tts`, that will use Nabu Casa's service. You'll need to revert to `google_translate` or use another TTS provider. The `base_url` config option can be used with any TTS provider.

**Comment by thomassandsor** [comment]
Changing it to google gives me:
![image](https://user-images.githubusercontent.com/33664322/144299090-e25786ab-1220-4390-b404-a3f6ea946db3.png)
I change the language to EN only
![image](https://user-images.githubusercontent.com/33664322/144299225-50bd43db-de90-4821-b0b0-52d3ecdbb7ea.png)
Then I also remove the gender

Suddenly it's working with the following setup:) 🎉🤗
tts:
  - platform: google_translate
    base_url: 'https://xxxxxx.duckdns.org:8123'
    language: en
    #gender: female

**Comment by jjlawren** [comment]
Yep, those additional options were specific to the `cloud` TTS provider. Glad you got it working!

**Comment by timknowlden** [comment]
Does sonos cloud api not work without nabu casa?

**Comment by Rocologo** [comment]
You should mention this in the dokumentation

https://github.com/jjlawren/sonos_cloud/issues/8#issuecomment-983843683

It helhed me to get tts.google_say work with Sonos Cloud.

Thank you for this integration!

**Comment by timknowlden** [comment]
> You should mention this in the dokumentation
> 
> [#8 (comment)](https://github.com/jjlawren/sonos_cloud/issues/8#issuecomment-983843683)
> 
> It helhed me to get tts.google_say work with Sonos Cloud.
> 
> Thank you for this integration!

I have google translate working but the snapshot will no longer restore. I can’t get this sonos cloud to work though. I don’t have nabu casa but use duckdns.

**Comment by Rocologo** [comment]
> 

I dont have nabu casa Esther. You just use tts.google_say and media_player.sonos_cloud_room and then it works.

**Comment by timknowlden** [comment]
brilliant, just used my original TTS call service node but pointed to the new Sonos entity. it does play the message twice but maybe I've got some investigating to do on that one!

**Comment by Rocologo** [comment]
> brilliant, just used my original TTS call service node but pointed to the new Sonos entity. it does play the message twice but maybe I've got some investigating to do on that one!

I only hear the message once.

**Comment by timknowlden** [comment]
> > brilliant, just used my original TTS call service node but pointed to the new Sonos entity. it does play the message twice but maybe I've got some investigating to do on that one!
> 
> I only hear the message once.

It was me... in node red I hadn't configured the trigger correctly. I had an input boolean triggering the TTS and then call service to turn off the input boolean after 5s. However the event state node for the input boolean I had it for any state change rather than ON. so when turned OFF it re-triggered.

**Comment by Rocologo** [comment]
Problem solved ☺️

**Comment by jjlawren** [comment]
> @jjlawren You should mention this in the dokumentation
> 
> [#8 (comment)](https://github.com/jjlawren/sonos_cloud/issues/8#issuecomment-983843683)
> 
> It helhed me to get tts.google_say work with Sonos Cloud.
> 
> Thank you for this integration!

@Rocologo  I've updated the "Limitations" section in the readme with a bit more more detail. Let me know if you have any other suggestions.

**Comment by Rocologo** [comment]
> > @jjlawren You should mention this in the dokumentation
> > [#8 (comment)](https://github.com/jjlawren/sonos_cloud/issues/8#issuecomment-983843683)
> > It helhed me to get tts.google_say work with Sonos Cloud.
> > Thank you for this integration!
> 
> @Rocologo I've updated the "Limitations" section in the readme with a bit more more detail. Let me know if you have any other suggestions.

I think "Limitations" is better now. When I realiced that I could use Google tts in combination with sonos_cloud it was easy to make it work. I thought I HAD to use tts.cloud_say.

**Comment by timknowlden** [comment]
> > > @jjlawren You should mention this in the dokumentation
> > > [#8 (comment)](https://github.com/jjlawren/sonos_cloud/issues/8#issuecomment-983843683)
> > > It helhed me to get tts.google_say work with Sonos Cloud.
> > > Thank you for this integration!
> > 
> > 
> > @Rocologo I've updated the "Limitations" section in the readme with a bit more more detail. Let me know if you have any other suggestions.
> 
> I think "Limitations" is better now. When I realiced that I could use Google tts in combination with sonos_cloud it was easy to make it work. I thought I HAD to use tts.cloud_say. I like that I can use tts.google_say because it speaks Danish :-)

That makes much more sense to me too. I also was under the impression I needed to use cloud_say with sonos cloud.
